services:
  backend:
    image: srinjay2004/ender-does-backend:latest
    container_name: ender-does-backend

    env_file:
      - .env

    ports:
      - "8081:8080"

    restart: unless-stopped

    networks:
      - apps

networks:
  apps:
    external: true
